name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.0.6+5
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mobx: ^2.2.0
  string_validator: ^1.0.0
  url_launcher: ^6.1.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/.env
